// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7GAVkgBhwrL4Km6VyW9QBmFf88D7u1g',
    appId: '1:398897716420:android:1519740edb7ef58b123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    databaseURL: 'https://dvij-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dvij-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12R-4a7E5g-NG5hcbzu--T5cNm57Fmbg',
    appId: '1:398897716420:ios:10422a71693d4aba123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    databaseURL: 'https://dvij-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dvij-flutter.appspot.com',
    iosBundleId: 'com.example.adminDvij',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB12R-4a7E5g-NG5hcbzu--T5cNm57Fmbg',
    appId: '1:398897716420:ios:10422a71693d4aba123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    databaseURL: 'https://dvij-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dvij-flutter.appspot.com',
    iosBundleId: 'com.example.adminDvij',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpDpRaxP2OHAHj3BCNnOPT5nm2Etw3OAo',
    appId: '1:398897716420:web:ad760a33a0581e50123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    authDomain: 'dvij-flutter.firebaseapp.com',
    databaseURL: 'https://dvij-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'dvij-flutter.appspot.com',
    measurementId: 'G-86NJ177FX9',
  );
}
